name: Cutter CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true # 'recursive' 'true' or 'false'
    - name: apt dependencies
      run: sudo apt-get install ninja-build libgraphviz-dev
    - name: Pipenv for Github Actions
      uses: VaultVulp/action-pipenv@v1.0.0
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        # Version range or exact version of a Python version to use, using semvers version range syntax.
        python-version: 3.7.5
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: x64
    - name: py dependencies
      run: |
        pip install meson
    #- name: cutter dependencies
    #  run: |
#       scripts/fetch_deps.sh
#       source cutter-deps/env.sh
#       export LD_LIBRARY_PATH="`llvm-config --libdir`:$LD_LIBRARY_PATH"
#       source scripts/prepare_breakpad_linux.sh
    - name: cmake
      run: |
        scripts/fetch_deps.sh
        source cutter-deps/env.sh
        export LD_LIBRARY_PATH="`llvm-config --libdir`:$LD_LIBRARY_PATH"
        source scripts/prepare_breakpad_linux.sh
        mkdir build
        cd build
        export PKG_CONFIG_PATH="$CUSTOM_BREAKPAD_PREFIX/lib/pkgconfig:$CUSTOM_PYTHON_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DPYTHON_LIBRARY="$CUTTER_DEPS_PYTHON_PREFIX/lib/libpython3.6m.so.1.0" \
                -DPYTHON_INCLUDE_DIR="$CUTTER_DEPS_PYTHON_PREFIX/include/python3.6m" \
                -DPYTHON_EXECUTABLE="$CUTTER_DEPS_PYTHON_PREFIX/bin/python3" \
                -DCUTTER_ENABLE_PYTHON=ON \
                -DCUTTER_ENABLE_PYTHON_BINDINGS=OFF \
                -DCUTTER_ENABLE_CRASH_REPORTS=ON \
                -DCUTTER_USE_BUNDLED_RADARE2=ON \
                ../src && \
        make -j4
